export const eventStat = [
  {
    index: 0,
    name: "work",
    displayName: "打工",
    dataName: "coins",
    imgSrc: "",
  },
  {
    index: 1,
    name: "lego",
    displayName: "玩樂高",
    dataName: "happiness",
    imgSrc: "",
    description: "",
    result: (number) => `played Lego. added ${number} on happniess`,
  },
  {
    index: 2,
    name: "mask",
    displayName: "fu mask",
    dataName: "beauty",
    imgSrc: "",
  },
  {
    index: 3,
    name: "sport",
    displayName: "健身",
    dataName: "sport",
    imgSrc: "",
  },
  {
    index: 4,
    name: "magic",
    女: "神秘的書本",
    dataName: "magic",
    imgSrc: "",
  },
  {
    index: 5,
    name: "read",
    displayName: "讀書",
    dataName: "wisdom",
    imgSrc: "",
  },
  {
    index: 6,
    name: "music",
    displayName: "聽音樂",
    dataName: "music",
    imgSrc: "",
  },
  {
    index: 7,
    name: "out",
    displayName: "出街",
    dataName: "love",
    imgSrc: "",
  },
  {
    index: 8,
    name: "animal",
    displayName: "和動物玩",
    dataName: "animal",
    imgSrc: "",
  },
];
