export const shopItemData = [
  {
    index: 0,
    name: "angel",
    displayName: "Angel Necklace",
    imgSrc: "",
    price: 1000,
    result: () => `Bough Angel Necklace. `,
  },
  {
    index: 1,
    name: "devil",
    displayName: "Devil Necklace",
    imgSrc: "",
    price: 1000,
    result: () => `Bough Devil Necklac. `,
  },
  {
    index: 2,
    name: "rabbit",
    displayName: "Rabbit Omamori",
    imgSrc: "",
    price: 1000,
  },
  {
    index: 3,
    name: "idol",
    displayName: "Agent Name Card",
    imgSrc: "",
    price: 1000,
  },
  {
    index: 4,
    name: "?",
    displayName: "?",
    imgSrc: "",
    price: 1000,
  },
  {
    index: 5,
    name: "bottle",
    displayName: "Bottled Medicine",
    imgSrc: "",
    price: 300,
    dataNameList: ["happiness", "beauty", "magic"],
    result: (number) =>
      `Bought Bottled Medicine. Added ${number} happiness, beauty, and magic.`,
  },
  {
    index: 6,
    name: "item2",
    displayName: "Item 2",
    imgSrc: "",
    price: 300,
    dataNameList: ["sport", "wisdom"],
  },
  {
    index: 7,
    name: "item3",
    displayName: "Item3",
    imgSrc: "",
    price: 300,
    dataNameList: ["music", "love", "animal"],
  },
  {
    index: 8,
    name: "super",
    displayName: "不知名的藥水",
    imgSrc: "",
    price: 200,
    result: (number) =>
      `Bought Bottled Medicine. Added ${number} happiness, beauty, and magic.`,
  },
];
